{% set name = "OnStove" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: db93f4812f1f270302e304a5df170b5d47be213feca9d239069c2a26822c3383

build: 
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
  run:
    - dill
    - geopandas
    - jupyterlab
    - matplotlib-base
    - mizani
    - pandas <3.0.0
    - plotnine >=0.12.2
    - psutil
    - psycopg2
    - pyproj
    - python >=3.10
    - python-decouple
    - rasterio
    - scikit-image
    - svgpathtools
    - svgpath2mpl

test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove
  summary: 'Python-based geospatial cost-benefit clean cooking tool, OnStove'
  description: |
    OnStove is a geospatial cost-benefit clean cooking tool that calculates 
    the net-benefits of different stove options in a given geography and compares 
    all stoves to one another with regards to their net-benefit.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://onstove-documentation.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove

extra:
  recipe-maintainers:
    - camiloramirezgo
    - babakkhavari
    - manuelsalslz
